name: Test

on:
  pull_request:
    paths-ignore:
      - LICENSE
      - README.md
  push:
    branches:
      - main

jobs:
  test:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Fix
        run: npm run fix

      - name: Commit
        id: commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@github.com
          message: Automatic commit via GitHub Actions

      - name: Test
        if: ${{ steps.commit.outputs.committed == 'false' }}
        run: npm run test
